version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: simple-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
   
  