version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: my-mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8082:8082'
    volumes:
      - data:/data
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=my-mongo
volumes:
  data: {}
networks:
  default:
    name: mongodb_network