spring:
  profiles:
    active: dev

  data:
    rest:
      base-path: /data-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
server:
  port: 8080
  
taco:
  orders:
    pageSize: 10


---    
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info
    org.springframework.web: info

---
spring:
  config:
    activate:
      on-profile: test  

logging:
  level:
    root: DEBUG
    org.springframework.web: warn